name: Trigger PipelineRun on Push

on:
  workflow_dispatch:
    inputs:
      pr_url:
        description: 'The PR URL that need to be merged to trigger the pipelinerun'
        required: true
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Enable Automerge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.inputs.pr_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}